# Generated by Django 3.0.8 on 2020-08-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chickens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chickens.Chicken')),
            ],
        ),
    ]
