# Generated by Django 3.0.8 on 2020-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeds_cost', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('no_of_birds', models.IntegerField()),
                ('small_equipment', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('paid_labor', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('transportation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('inKind_expenses', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
    ]
