# Generated by Django 3.0.8 on 2020-10-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('application_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('application_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('control', models.TextField(max_length=250)),
                ('drugs', models.ManyToManyField(to='procedures.Drugs')),
                ('vaccine', models.ManyToManyField(null=True, to='procedures.Vaccine')),
            ],
        ),
    ]
